DEFAULT_REPLY = (
    "Thanks for reaching out. We are reviewing your request and will guide you through the next steps."
)


REPLY_TEMPLATES = {
    "activate_my_card": "Please open the card section in the app and follow the activation steps.",
    "age_limit": "Our team can help confirm the age requirements for opening and using an account.",
    "apple_pay_or_google_pay": "Please check that your card is active and add it again to Apple Pay or Google Pay.",
    "atm_support": "Please share the ATM location, date, and transaction details so we can look into it.",
    "automatic_top_up": "You can review or change automatic top up settings in the app top up section.",
    "balance_not_updated_after_bank_transfer": "Bank transfers can take time to appear; please share the transfer details if it is delayed.",
    "balance_not_updated_after_cheque_or_cash_deposit": "Cash and cheque deposits may take time to process; please share the deposit details if needed.",
    "beneficiary_not_allowed": "Please check the recipient details and supported transfer rules before trying again.",
    "cancel_transfer": "If the transfer is still pending, we can help check whether cancellation is possible.",
    "card_about_to_expire": "We will help you review your card expiry and replacement options.",
    "card_acceptance": "Please confirm where the card was declined so we can check acceptance and merchant details.",
    "card_arrival": "Your card may still be in transit; please check the delivery estimate in the app.",
    "card_delivery_estimate": "You can see the latest card delivery estimate in the card section of the app.",
    "card_linking": "Please make sure the card details are correct and try linking the card again.",
    "card_not_working": "Please try another payment method and share what happened so we can investigate your card issue.",
    "card_payment_fee_charged": "We can review the card payment fee and explain why it appeared on your statement.",
    "card_payment_not_recognised": "Please freeze your card if needed and report the unrecognized payment in the app.",
    "card_payment_wrong_exchange_rate": "We can check the exchange rate used for this card payment and explain the calculation.",
    "card_swallowed": "Please contact the ATM provider and freeze your card in the app if you are concerned.",
    "cash_withdrawal_charge": "We can review the cash withdrawal fee and explain any charges applied.",
    "cash_withdrawal_not_recognised": "Please secure your card and report the unrecognized cash withdrawal immediately.",
    "change_pin": "You can change your PIN in the card settings or at a supported ATM.",
    "compromised_card": "Please freeze your card immediately and we will help you secure your account.",
    "contactless_not_working": "Please try chip and PIN once, then retry contactless after the card is confirmed active.",
    "country_support": "We can help confirm whether our services are available in your country.",
    "declined_card_payment": "Please check your balance, card status, and payment limits before trying again.",
    "declined_cash_withdrawal": "Please check your cash withdrawal limits, balance, and ATM support.",
    "declined_transfer": "Please review the recipient details and available balance, then try the transfer again.",
    "direct_debit_payment_not_recognised": "Please review the direct debit details and report it if you do not recognize it.",
    "disposable_card_limits": "Disposable virtual cards have usage limits; we can help explain the current limits.",
    "edit_personal_details": "You can update personal details in the profile section or contact support for restricted changes.",
    "exchange_charge": "We can explain the exchange fee and how it was calculated for your transaction.",
    "exchange_rate": "The exchange rate is shown in the app before you confirm an exchange.",
    "exchange_via_app": "You can exchange currency directly in the app from the exchange section.",
    "extra_charge_on_statement": "We can review the extra charge and help identify why it appeared on your statement.",
    "failed_transfer": "Please check the transfer details and try again; we can investigate if it continues to fail.",
    "fiat_currency_support": "We can confirm which fiat currencies are currently supported.",
    "get_disposable_virtual_card": "You can create a disposable virtual card from the cards section in the app.",
    "get_physical_card": "You can order a physical card from the cards section in the app.",
    "getting_spare_card": "We can help you order or review options for a spare card.",
    "getting_virtual_card": "You can create a virtual card in the cards section of the app.",
    "lost_or_stolen_card": "Please freeze your card immediately and report it as lost or stolen in the app.",
    "lost_or_stolen_phone": "Please secure your account and contact support if your phone was lost or stolen.",
    "order_physical_card": "You can order a physical card from the cards section and confirm your delivery address.",
    "passcode_forgotten": "Please use the app recovery flow to reset your passcode securely.",
    "pending_card_payment": "Pending card payments usually update automatically once the merchant confirms or releases them.",
    "pending_cash_withdrawal": "A pending cash withdrawal should update after the ATM provider confirms the transaction.",
    "pending_top_up": "Your top up is pending and should update once the payment provider confirms it.",
    "pending_transfer": "Your transfer is pending and should complete after the banking network processes it.",
    "pin_blocked": "You can unblock or reset your PIN using the card settings or a supported ATM.",
    "receiving_money": "We can help you find the right account details to receive money.",
    "Refund_not_showing_up": "Refunds can take several days to appear; please share the merchant and date if delayed.",
    "request_refund": "Please provide the transaction details so we can guide you through the refund request.",
    "reverted_card_payment?": "A reverted card payment should return to your balance after processing completes.",
    "supported_cards_and_currencies": "We can confirm which cards and currencies are supported for your account.",
    "terminate_account": "We can help you understand the steps required to close your account.",
    "top_up_by_bank_transfer_charge": "We can explain any charge related to topping up by bank transfer.",
    "top_up_by_card_charge": "We can review the card top up charge and explain why it was applied.",
    "top_up_by_cash_or_cheque": "Cash or cheque top ups may take time to process; please share the deposit details if delayed.",
    "top_up_failed": "Please check the payment method and try again; we can investigate if the top up keeps failing.",
    "top_up_limits": "You can review top up limits in the app, and we can help explain any restrictions.",
    "top_up_reverted": "A reverted top up should return to the original payment method after processing.",
    "topping_up_by_card": "You can top up by card in the app by choosing card as the payment method.",
    "transaction_charged_twice": "We can review the duplicate charge and help confirm whether one payment will be reversed.",
    "transfer_fee_charged": "We can explain the transfer fee and why it was applied.",
    "transfer_into_account": "Please use your account details in the app to transfer money into your account.",
    "transfer_not_received_by_recipient": "Please share the transfer details so we can check why the recipient has not received it.",
    "transfer_timing": "Transfer timing depends on the currency, destination, and banking network used.",
    "unable_to_verify_identity": "Please check that your documents are clear and match your account details.",
    "verify_my_identity": "Please follow the identity verification steps in the app and upload the requested documents.",
    "verify_source_of_funds": "Please provide the requested documents so we can verify the source of funds.",
    "verify_top_up": "We may need extra details to verify this top up before it can be completed.",
    "virtual_card_not_working": "Please check that your virtual card is active and try the payment again.",
    "visa_or_mastercard": "We can confirm whether your card is issued as Visa or Mastercard.",
    "why_verify_identity": "Identity verification helps keep your account secure and meet regulatory requirements.",
    "wrong_amount_of_cash_received": "Please share the ATM location, date, and amount received so we can investigate.",
    "wrong_exchange_rate_for_cash_withdrawal": "We can review the exchange rate used for your cash withdrawal.",
}


def get_suggested_reply(intent: str) -> str:
    return REPLY_TEMPLATES.get(intent, DEFAULT_REPLY)
